@startuml

actor Клиент
actor Менеджер order 20
actor Повар order 30
actor Курьер order 60

boundary Сайт order 10
boundary Терминал order 63
control Сервис_Асортимента order 11
control Чекаут order 13
control Сервис_Корзины order 12
control Сервис_Авторизации order 15
database CRM order 18
control СУ_Доставкой order 40
control Сервис_оплаты order 65
control СУ_заказами order 16

activate Клиент
Клиент -> Сайт : Зайти на сайт
activate Сайт
Сайт -> Сервис_Асортимента : Запрос ассортимента
activate Сервис_Асортимента
Сервис_Асортимента --> Сайт : Список ассортимента
deactivate Сервис_Асортимента
Сайт --> Клиент : Отобразить список позиций
Loop  Хватит пиццы
Клиент -> Сайт : Добавить позицию в корзину
Сайт -> Сервис_Корзины : Детали позиции
activate Сервис_Корзины
Сервис_Корзины --> Сайт : Пицца в корзине
Сайт --> Клиент : Отобразить изменение корзины
End  
Клиент -> Сайт : Перейти в корзину
Сайт -> Сервис_Корзины : Запрос корзины
Сервис_Корзины --> Сайт : Состав корзины
deactivate Сервис_Корзины
Сайт --> Клиент : Состав заказа
Клиент -> Сайт : Оформить заказ
Сайт -> Чекаут : Оформить заказ
activate Чекаут 
Чекаут -> Сервис_Авторизации : Запрос авторизации
activate Сервис_Авторизации 
Сервис_Авторизации --> Чекаут : Клиент авторизован
deactivate Сервис_Авторизации 
Чекаут -> CRM : Запрос данных клиента
CRM --> Чекаут : Данные клиента
Чекаут -> СУ_заказами : Создание заказа
activate СУ_заказами
СУ_заказами --> Чекаут : № заказа
СУ_заказами ->> CRM : Данные заказа
Чекаут --> Сайт : № заказа
deactivate Чекаут 
Сайт --> Клиент : № заказа
deactivate Сайт 
СУ_заказами -> Менеджер : Проверка заказа
activate Менеджер 
Менеджер --> СУ_заказами : Подтверждение заказа
deactivate Менеджер 
СУ_заказами -> Повар : Детали заказа
activate Повар
Повар --> СУ_заказами : Заказ готов
deactivate Повар
СУ_заказами -> СУ_Доставкой : Детали заказа
activate СУ_Доставкой
СУ_Доставкой -> Курьер : Назначить заказ курьеру
activate Курьер
Курьер --> СУ_Доставкой : Заказ забрал
Курьер -> Курьер : Доставка заказа
Курьер -> Терминал : Запрос оплаты
activate Терминал
Терминал -> Сервис_оплаты : Детали оплаты
activate Сервис_оплаты
Сервис_оплаты --> Терминал : Запрос данных карты
Клиент -> Терминал : Карта
Терминал -> Сервис_оплаты : Оплата
Сервис_оплаты --> Терминал : Распечатать чек
Сервис_оплаты ->> CRM : Данные оплаты
deactivate Сервис_оплаты
Терминал --> Курьер : Чек
deactivate Терминал 
Курьер -> СУ_Доставкой : Заказ доставлен
deactivate Курьер
СУ_Доставкой --> СУ_заказами : Заказ доставлен
deactivate СУ_Доставкой
СУ_заказами --> Клиент : Уведомление о доставке заказа
deactivate СУ_заказами
deactivate Клиент

@enduml
